# Generated by Django 5.2.1 on 2025-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_auto_20190510_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
