# Generated by Django 4.2.8 on 2025-07-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_add_workflow_step_permissions"),
        ("rbac", "0003_alter_menu_id_alter_permission_id_alter_role_id"),
    ]

    operations = []
