# Generated by Django 4.2.8 on 2025-07-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0004_merge_20250711_1716"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowstepoperationlog",
            new_name="rbac_workfl_order_n_fb5e3a_idx",
            old_name="rbac_workfl_order_n_b9a6c1_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstepoperationlog",
            new_name="rbac_workfl_operato_37ad94_idx",
            old_name="rbac_workfl_operato_a1b5f8_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstepoperationlog",
            new_name="rbac_workfl_step_na_7c69d6_idx",
            old_name="rbac_workfl_step_na_7e4c6d_idx",
        ),
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="图标"
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepoperationlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsteppermission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsteppermissiontype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
