# Generated by Django 2.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下单日期')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='交货日期')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已取消')], default=1, verbose_name='订单状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PrintProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.IntegerField(choices=[(1, '封面印刷'), (2, '内文印刷')], verbose_name='流程类型')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('status', models.IntegerField(choices=[(1, '待开始'), (2, '进行中'), (3, '已完成'), (4, '已暂停')], default=1, verbose_name='流程状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='操作员')),
                ('print_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PrintOrder', verbose_name='印刷订单')),
            ],
        ),
        migrations.CreateModel(
            name='PrintProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('step_order', models.IntegerField(verbose_name='步骤顺序')),
                ('status', models.IntegerField(choices=[(1, '待确认'), (2, '已确认'), (3, '已跳过')], default=1, verbose_name='步骤状态')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='确认人')),
                ('print_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PrintProcess', verbose_name='印刷流程')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ] 