# Generated by Django 5.2.1 on 2025-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_add_print_models"),
        ("crm", "0046_auto_20190519_1139"),
    ]

    operations = []
