# Generated by Django 5.2.1 on 2025-07-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0047_merge_0002_add_print_models_0046_auto_20190519_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorder",
            name="customer_supply",
            field=models.TextField(blank=True, null=True, verbose_name="客户提供"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="delivery_pack_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="送货和包装要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="design_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="设计制作要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="imposition_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="拼晒要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="print_tech_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="印刷工艺要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="product_description",
            field=models.TextField(blank=True, null=True, verbose_name="产品描述"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="product_size",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="成品尺寸"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="salesman",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="业务员"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="订货单位"
            ),
        ),
        migrations.AlterField(
            model_name="printorder",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="委印日期"),
        ),
        migrations.AlterField(
            model_name="printorder",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="印品名称"),
        ),
        migrations.AlterField(
            model_name="printorder",
            name="quantity",
            field=models.IntegerField(verbose_name="订货数量"),
        ),
        migrations.CreateModel(
            name="PrintMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="序号"
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材料名称"
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "page_print",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="页印"
                    ),
                ),
                (
                    "paper",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="用纸"
                    ),
                ),
                (
                    "zhengshu",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="正数"
                    ),
                ),
                (
                    "fangshu",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="放数"
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="总数"
                    ),
                ),
                (
                    "dunjia",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="吨价"
                    ),
                ),
                (
                    "unit_price",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="金额"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.printorder",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintPostpress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="序号"
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目"
                    ),
                ),
                (
                    "process_content",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="加工内容"
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工序"
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="机台"
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="金额"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.printorder",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintPrepress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="序号"
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="内容"
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "plate_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制版名称"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="金额"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.printorder",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintProcessDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="序号"
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目"
                    ),
                ),
                (
                    "print_color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印色"
                    ),
                ),
                (
                    "print_size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印刷尺寸"
                    ),
                ),
                (
                    "print_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印刷方式"
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="机台"
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="金额"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.printorder",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属分区"
                    ),
                ),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                (
                    "step_order",
                    models.IntegerField(blank=True, null=True, verbose_name="步骤顺序"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待确认"), (2, "已确认"), (3, "已跳过")],
                        default=1,
                        verbose_name="步骤状态",
                    ),
                ),
                (
                    "confirm_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "confirm_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.userinfo",
                        verbose_name="确认人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.printorder",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
            },
        ),
    ]
