# Generated by Django 5.2.1 on 2025-07-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0048_printorder_customer_supply_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printmaterial",
            name="dunjia",
        ),
        migrations.RemoveField(
            model_name="printmaterial",
            name="page_print",
        ),
        migrations.RemoveField(
            model_name="printmaterial",
            name="paper",
        ),
        migrations.RemoveField(
            model_name="printmaterial",
            name="zhengshu",
        ),
        migrations.RemoveField(
            model_name="printorder",
            name="imposition_requirement",
        ),
        migrations.AddField(
            model_name="printmaterial",
            name="open_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="开数"
            ),
        ),
        migrations.AddField(
            model_name="printmaterial",
            name="page_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="页数"
            ),
        ),
        migrations.AddField(
            model_name="printmaterial",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="单位"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="auditor",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="审核人"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="consumption_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="消耗要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="联系人"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="联系方式"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="customer_signature",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="客户签字"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="footer_note",
            field=models.TextField(blank=True, null=True, verbose_name="底部备注"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="order_maker",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="制单员"
            ),
        ),
        migrations.AddField(
            model_name="printorder",
            name="quality_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="质检要求"),
        ),
        migrations.AddField(
            model_name="printorder",
            name="work_order_no",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="工单号"
            ),
        ),
        migrations.AddField(
            model_name="printpostpress",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="单位"
            ),
        ),
        migrations.AddField(
            model_name="printprepress",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="单位"
            ),
        ),
        migrations.AddField(
            model_name="printprocessdetail",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="单位"
            ),
        ),
    ]
