# Generated by Django 5.2.1 on 2025-07-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0049_remove_printmaterial_dunjia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printorder",
            name="product_size",
            field=models.TextField(blank=True, null=True, verbose_name="成品尺寸"),
        ),
    ]
