# Generated by Django 5.2.1 on 2025-07-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0050_alter_printorder_product_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintOrderFlat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=32, verbose_name="订单编号")),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="客户名称"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="印品名称"
                    ),
                ),
                (
                    "product_size",
                    models.TextField(blank=True, null=True, verbose_name="成品尺寸"),
                ),
                (
                    "order_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="委印日期"),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="交货日期"),
                ),
                (
                    "salesman",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="业务员"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "design_requirement",
                    models.TextField(blank=True, null=True, verbose_name="设计制作要求"),
                ),
                (
                    "customer_supply",
                    models.TextField(blank=True, null=True, verbose_name="客户提供"),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, null=True, verbose_name="产品描述"),
                ),
                (
                    "consumption_requirement",
                    models.TextField(blank=True, null=True, verbose_name="消耗要求"),
                ),
                (
                    "print_tech_requirement",
                    models.TextField(blank=True, null=True, verbose_name="印刷工艺要求"),
                ),
                (
                    "quality_requirement",
                    models.TextField(blank=True, null=True, verbose_name="质检要求"),
                ),
                (
                    "delivery_pack_requirement",
                    models.TextField(blank=True, null=True, verbose_name="送货和包装要求"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "customer_signature",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="客户签字"
                    ),
                ),
                (
                    "order_maker",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="制单员"
                    ),
                ),
                (
                    "auditor",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="审核人"
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="订货数量"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="订货单位"
                    ),
                ),
                (
                    "detail_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="明细类型"
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="序号"
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材料名称"
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "page_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="页数"
                    ),
                ),
                (
                    "open_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="开数"
                    ),
                ),
                (
                    "fangshu",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="放数"
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="总数"
                    ),
                ),
                (
                    "dunjia",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="吨价"
                    ),
                ),
                (
                    "unit_price",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="金额"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="内容"
                    ),
                ),
                (
                    "plate_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制版名称"
                    ),
                ),
                (
                    "note_detail",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="明细备注"
                    ),
                ),
                (
                    "print_color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印色"
                    ),
                ),
                (
                    "print_size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印刷尺寸"
                    ),
                ),
                (
                    "print_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="印刷方式"
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="机台"
                    ),
                ),
                (
                    "process_content",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="加工内容"
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工序"
                    ),
                ),
            ],
            options={
                "verbose_name": "订单全信息大表",
                "verbose_name_plural": "订单全信息大表",
            },
        ),
    ]
