# Generated by Django 5.2.1 on 2025-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_printorderflat"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorderflat",
            name="material_json",
            field=models.TextField(blank=True, null=True, verbose_name="用料明细JSON"),
        ),
        migrations.AddField(
            model_name="printorderflat",
            name="postpress_json",
            field=models.TextField(blank=True, null=True, verbose_name="印后明细JSON"),
        ),
        migrations.AddField(
            model_name="printorderflat",
            name="prepress_json",
            field=models.TextField(blank=True, null=True, verbose_name="印前明细JSON"),
        ),
        migrations.AddField(
            model_name="printorderflat",
            name="process_json",
            field=models.TextField(blank=True, null=True, verbose_name="印刷明细JSON"),
        ),
    ]
