# Generated by Django 5.2.1 on 2025-07-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0052_printorderflat_material_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorderflat",
            name="imposition_requirement",
            field=models.TextField(blank=True, null=True, verbose_name="拼晒要求"),
        ),
    ]
