# Generated by Django 5.2.1 on 2025-07-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0053_printorderflat_imposition_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printorderflat",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="content",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="dunjia",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="fangshu",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="item",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="material_name",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="note_detail",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="open_number",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="page_number",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="plate_name",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="print_color",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="print_method",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="print_size",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="process",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="process_content",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="serial_no",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="spec",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="total",
        ),
        migrations.RemoveField(
            model_name="printorderflat",
            name="unit_price",
        ),
    ]
