# Generated by Django 5.2.1 on 2025-07-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0054_remove_printorderflat_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorderflat",
            name="print_type",
            field=models.CharField(
                choices=[("cover", "封面印刷"), ("content", "内文印刷"), ("both", "封面+内文")],
                default="cover",
                max_length=20,
                verbose_name="印刷类型",
            ),
        ),
        migrations.AddField(
            model_name="printorderflat",
            name="status",
            field=models.IntegerField(
                choices=[(1, "待处理"), (2, "处理中"), (3, "已完成"), (4, "已取消")],
                default=1,
                verbose_name="订单状态",
            ),
        ),
        migrations.CreateModel(
            name="OrderProgressTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "print_type",
                    models.CharField(
                        choices=[
                            ("cover", "封面印刷"),
                            ("content", "内文印刷"),
                            ("both", "封面+内文"),
                        ],
                        max_length=20,
                        verbose_name="印刷类型",
                    ),
                ),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="步骤描述"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必需步骤"),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(default=1, verbose_name="预计耗时(小时)"),
                ),
            ],
            options={
                "ordering": ["print_type", "step_order"],
                "unique_together": {("print_type", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="OrderProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待开始"), (2, "进行中"), (3, "已完成"), (4, "已跳过")],
                        default=1,
                        verbose_name="步骤状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "confirm_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_steps",
                        to="crm.userinfo",
                        verbose_name="确认人",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operated_steps",
                        to="crm.userinfo",
                        verbose_name="操作员",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_steps",
                        to="crm.printorderflat",
                        verbose_name="印刷订单",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
                "unique_together": {("order", "step_order")},
            },
        ),
    ]
