# Generated by Django 4.2.8 on 2025-07-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0058_alter_orderprogresstemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printorderflat",
            name="order_no",
            field=models.CharField(max_length=32, unique=True, verbose_name="订单编号"),
        ),
    ]
