# Generated by Django 4.2.8 on 2025-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0059_alter_printorderflat_order_no"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderprogress",
            name="step_category",
            field=models.CharField(
                choices=[("cover", "封面"), ("content", "内文")],
                default="content",
                max_length=20,
                verbose_name="步骤分类",
            ),
        ),
        migrations.AlterField(
            model_name="orderprogresstemplate",
            name="print_type",
            field=models.CharField(
                choices=[
                    ("cover", "封面印刷"),
                    ("content", "内文印刷"),
                    ("cover_content", "封面+内文"),
                ],
                max_length=20,
                verbose_name="印刷类型",
            ),
        ),
        migrations.AlterField(
            model_name="printorderflat",
            name="print_type",
            field=models.CharField(
                choices=[
                    ("cover", "封面印刷"),
                    ("content", "内文印刷"),
                    ("cover_content", "封面+内文"),
                ],
                default="cover",
                max_length=20,
                verbose_name="印刷类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderprogress",
            unique_together={("order", "step_order", "step_category")},
        ),
    ]
